//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/application.go:7

package spicegen

// ApplicationTargetCompositionProof_94ab0f70 identifies the generated target selected by spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|16:CompositionProof.
const ApplicationTargetCompositionProof_94ab0f70 = "compositionproof"
