//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/cleanup.go:15

package spicegen

import (
	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructCleanup_9786bbb9 performs the direct construction selected for bean "cleanup".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|13:NewCleanupLog.
func ConstructCleanup_9786bbb9() (*compositionfixture.CleanupLog, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewCleanupLog()
	return value, nil, nil
}
