//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/proof.go:32

package spicegen

import (
	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructProof_7ff50430 performs the direct construction selected for bean "proof".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|8:NewProof.
func ConstructProof_7ff50430(dependency0 compositionfixture.ProviderAlias, dependency1 []compositionfixture.TextStage, dependency2 compositionfixture.FallbackStage, dependency3 compositionfixture.ReplaceableStage, dependency4 map[string]compositionfixture.ToolAlias, dependency5 []stage.ToolDispatchGuard, dependency6 *compositionfixture.DispatchGuardLog, dependency7 compositionfixture.ToolAlias, dependency8 *compositionfixture.CleanupLog) (*compositionfixture.Proof, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewProof(dependency0, dependency1, dependency2, dependency3, dependency4, dependency5, dependency6, dependency7, dependency8)
	return value, nil, nil
}
