//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/providers.go:38
// Source: internal/compositionfixture/providers.go:45
// Source: internal/compositionfixture/providers.go:52

package spicegen

import (
	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructBeta_e793250c performs the direct construction selected for bean "beta".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|15:NewBetaProvider.
func ConstructBeta_e793250c() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewBetaProvider()
	return value, nil, nil
}

// ConstructAlpha_a5938712 performs the direct construction selected for bean "alpha".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|16:NewAlphaProvider.
func ConstructAlpha_a5938712() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewAlphaProvider()
	return value, nil, nil
}

// ConstructFallback_2be0b785 performs the direct construction selected for bean "fallback".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewFallbackProvider.
func ConstructFallback_2be0b785() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewFallbackProvider()
	return value, nil, nil
}
