//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/stages.go:32
// Source: internal/compositionfixture/stages.go:39
// Source: internal/compositionfixture/stages.go:46
// Source: internal/compositionfixture/stages.go:53
// Source: internal/compositionfixture/stages.go:60

package spicegen

import (
	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructTrim_cb8b0647 performs the direct construction selected for bean "trim".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewTrimStage.
func ConstructTrim_cb8b0647() (compositionfixture.TextStage, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewTrimStage()
	return value, nil, nil
}

// ConstructSuffix_def7d22b performs the direct construction selected for bean "suffix".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|14:NewSuffixStage.
func ConstructSuffix_def7d22b() (compositionfixture.TextStage, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewSuffixStage()
	return value, nil, nil
}

// ConstructFallbackOnly_7f31930c performs the direct construction selected for bean "fallback-only".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|20:NewFallbackOnlyStage.
func ConstructFallbackOnly_7f31930c() (compositionfixture.FallbackStage, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewFallbackOnlyStage()
	return value, nil, nil
}

// ConstructReplaceableNormal_bf8e8d0b performs the direct construction selected for bean "replaceable-normal".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|25:NewReplaceableNormalStage.
func ConstructReplaceableNormal_bf8e8d0b() (compositionfixture.ReplaceableStage, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewReplaceableNormalStage()
	return value, nil, nil
}

// ConstructReplaceableDefault_c1a89b56 performs the direct construction selected for bean "replaceable-default".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|26:NewReplaceableDefaultStage.
func ConstructReplaceableDefault_c1a89b56() (compositionfixture.ReplaceableStage, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewReplaceableDefaultStage()
	return value, nil, nil
}
