//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: internal/compositionfixture/tools.go:23
// Source: internal/compositionfixture/tools.go:42
// Source: internal/compositionfixture/tools.go:86
// Source: internal/compositionfixture/tools.go:100

package spicegen

import (
	fmt "fmt"

	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	stage "github.com/spice-framework/spice-agent/stage"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructRead_78da3a75 performs the direct construction selected for bean "read".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|11:NewReadTool.
func ConstructRead_78da3a75(dependency0 *compositionfixture.CleanupLog) (compositionfixture.ToolAlias, spicelifecycle.Cleanup, error) {
	value, cleanup, err := compositionfixture.NewReadTool(dependency0)
	if err != nil {
		var zero compositionfixture.ToolAlias
		return zero, nil, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/internal/compositionfixture.ToolAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|11:NewReadTool): %w", err)
	}
	return value, cleanup, nil
}

// ConstructWrite_00e73c36 performs the direct construction selected for bean "write".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewWriteTool.
func ConstructWrite_00e73c36(dependency0 *compositionfixture.CleanupLog, dependency1 compositionfixture.ToolAlias) (compositionfixture.ToolAlias, spicelifecycle.Cleanup, error) {
	value, cleanup, err := compositionfixture.NewWriteTool(dependency0, dependency1)
	if err != nil {
		var zero compositionfixture.ToolAlias
		return zero, nil, fmt.Errorf("construct bean write (github.com/spice-framework/spice-agent/internal/compositionfixture.ToolAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewWriteTool): %w", err)
	}
	return value, cleanup, nil
}

// ConstructDispatchGuardLog_797b8bbb performs the direct construction selected for bean "dispatchGuardLog".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewDispatchGuardLog.
func ConstructDispatchGuardLog_797b8bbb() (*compositionfixture.DispatchGuardLog, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewDispatchGuardLog()
	return value, nil, nil
}

// ConstructFixtureDispatchGuard_70698017 performs the direct construction selected for bean "fixtureDispatchGuard".
// Spice source identity: spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|23:NewFixtureDispatchGuard.
func ConstructFixtureDispatchGuard_70698017(dependency0 *compositionfixture.DispatchGuardLog) (stage.ToolDispatchGuard, spicelifecycle.Cleanup, error) {
	value := compositionfixture.NewFixtureDispatchGuard(dependency0)
	return value, nil, nil
}
