//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	spiceCompositionfixture "github.com/spice-framework/spice-agent/internal/spicegen/compositionproof/sources/internal_/compositionfixture"
	stage "github.com/spice-framework/spice-agent/stage"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

type applicationDependencies struct {
	trim                 compositionfixture.TextStage
	cleanup              *compositionfixture.CleanupLog
	read                 compositionfixture.ToolAlias
	write                compositionfixture.ToolAlias
	suffix               compositionfixture.TextStage
	beta                 compositionfixture.ProviderAlias
	alpha                compositionfixture.ProviderAlias
	dispatchGuardLog     *compositionfixture.DispatchGuardLog
	fallback             compositionfixture.ProviderAlias
	fallbackOnly         compositionfixture.FallbackStage
	fixtureDispatchGuard stage.ToolDispatchGuard
	replaceableNormal    compositionfixture.ReplaceableStage
	replaceableDefault   compositionfixture.ReplaceableStage
	proof                *compositionfixture.Proof
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	trim, trimCleanup, err := func() (compositionfixture.TextStage, spicelifecycle.Cleanup, error) {
		if options.Overrides.Trim.Enabled() {
			return options.Overrides.Trim.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructTrim_cb8b0647()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean trim (github.com/spice-framework/spice-agent/internal/compositionfixture.TextStage, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewTrimStage): %w", err))
	}
	if trimCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewTrimStage", trimCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean trim (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewTrimStage): %w", err))
		}
	}
	_ = trim
	cleanup, cleanupCleanup, err := func() (*compositionfixture.CleanupLog, spicelifecycle.Cleanup, error) {
		if options.Overrides.Cleanup.Enabled() {
			return options.Overrides.Cleanup.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructCleanup_9786bbb9()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean cleanup (*github.com/spice-framework/spice-agent/internal/compositionfixture.CleanupLog, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|13:NewCleanupLog): %w", err))
	}
	if cleanupCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|13:NewCleanupLog", cleanupCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean cleanup (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|13:NewCleanupLog): %w", err))
		}
	}
	_ = cleanup
	read, readCleanup, err := func() (compositionfixture.ToolAlias, spicelifecycle.Cleanup, error) {
		if options.Overrides.Read.Enabled() {
			return options.Overrides.Read.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructRead_78da3a75(cleanup)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean read (github.com/spice-framework/spice-agent/internal/compositionfixture.ToolAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|11:NewReadTool): %w", err))
	}
	if readCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|11:NewReadTool", readCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean read (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|11:NewReadTool): %w", err))
		}
	}
	_ = read
	write, writeCleanup, err := func() (compositionfixture.ToolAlias, spicelifecycle.Cleanup, error) {
		if options.Overrides.Write.Enabled() {
			return options.Overrides.Write.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructWrite_00e73c36(cleanup, read)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean write (github.com/spice-framework/spice-agent/internal/compositionfixture.ToolAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewWriteTool): %w", err))
	}
	if writeCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewWriteTool", writeCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean write (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|12:NewWriteTool): %w", err))
		}
	}
	_ = write
	suffix, suffixCleanup, err := func() (compositionfixture.TextStage, spicelifecycle.Cleanup, error) {
		if options.Overrides.Suffix.Enabled() {
			return options.Overrides.Suffix.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructSuffix_def7d22b()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean suffix (github.com/spice-framework/spice-agent/internal/compositionfixture.TextStage, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|14:NewSuffixStage): %w", err))
	}
	if suffixCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|14:NewSuffixStage", suffixCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean suffix (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|14:NewSuffixStage): %w", err))
		}
	}
	_ = suffix
	beta, betaCleanup, err := func() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
		if options.Overrides.Beta.Enabled() {
			return options.Overrides.Beta.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructBeta_e793250c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean beta (github.com/spice-framework/spice-agent/internal/compositionfixture.ProviderAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|15:NewBetaProvider): %w", err))
	}
	if betaCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|15:NewBetaProvider", betaCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean beta (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|15:NewBetaProvider): %w", err))
		}
	}
	_ = beta
	alpha, alphaCleanup, err := func() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
		if options.Overrides.Alpha.Enabled() {
			return options.Overrides.Alpha.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructAlpha_a5938712()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean alpha (github.com/spice-framework/spice-agent/internal/compositionfixture.ProviderAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|16:NewAlphaProvider): %w", err))
	}
	if alphaCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|16:NewAlphaProvider", alphaCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean alpha (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|16:NewAlphaProvider): %w", err))
		}
	}
	_ = alpha
	dispatchGuardLog, dispatchGuardLogCleanup, err := func() (*compositionfixture.DispatchGuardLog, spicelifecycle.Cleanup, error) {
		if options.Overrides.DispatchGuardLog.Enabled() {
			return options.Overrides.DispatchGuardLog.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructDispatchGuardLog_797b8bbb()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean dispatchGuardLog (*github.com/spice-framework/spice-agent/internal/compositionfixture.DispatchGuardLog, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewDispatchGuardLog): %w", err))
	}
	if dispatchGuardLogCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewDispatchGuardLog", dispatchGuardLogCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean dispatchGuardLog (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewDispatchGuardLog): %w", err))
		}
	}
	_ = dispatchGuardLog
	fallback, fallbackCleanup, err := func() (compositionfixture.ProviderAlias, spicelifecycle.Cleanup, error) {
		if options.Overrides.Fallback.Enabled() {
			return options.Overrides.Fallback.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructFallback_2be0b785()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean fallback (github.com/spice-framework/spice-agent/internal/compositionfixture.ProviderAlias, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewFallbackProvider): %w", err))
	}
	if fallbackCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewFallbackProvider", fallbackCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean fallback (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|19:NewFallbackProvider): %w", err))
		}
	}
	_ = fallback
	fallbackOnly, fallbackOnlyCleanup, err := func() (compositionfixture.FallbackStage, spicelifecycle.Cleanup, error) {
		if options.Overrides.Provider9.Enabled() {
			return options.Overrides.Provider9.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructFallbackOnly_7f31930c()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean fallback-only (github.com/spice-framework/spice-agent/internal/compositionfixture.FallbackStage, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|20:NewFallbackOnlyStage): %w", err))
	}
	if fallbackOnlyCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|20:NewFallbackOnlyStage", fallbackOnlyCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean fallback-only (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|20:NewFallbackOnlyStage): %w", err))
		}
	}
	_ = fallbackOnly
	fixtureDispatchGuard, fixtureDispatchGuardCleanup, err := func() (stage.ToolDispatchGuard, spicelifecycle.Cleanup, error) {
		if options.Overrides.FixtureDispatchGuard.Enabled() {
			return options.Overrides.FixtureDispatchGuard.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructFixtureDispatchGuard_70698017(dispatchGuardLog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean fixtureDispatchGuard (github.com/spice-framework/spice-agent/stage.ToolDispatchGuard, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|23:NewFixtureDispatchGuard): %w", err))
	}
	if fixtureDispatchGuardCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|23:NewFixtureDispatchGuard", fixtureDispatchGuardCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean fixtureDispatchGuard (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|23:NewFixtureDispatchGuard): %w", err))
		}
	}
	_ = fixtureDispatchGuard
	replaceableNormal, replaceableNormalCleanup, err := func() (compositionfixture.ReplaceableStage, spicelifecycle.Cleanup, error) {
		if options.Overrides.Provider11.Enabled() {
			return options.Overrides.Provider11.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructReplaceableNormal_bf8e8d0b()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replaceable-normal (github.com/spice-framework/spice-agent/internal/compositionfixture.ReplaceableStage, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|25:NewReplaceableNormalStage): %w", err))
	}
	if replaceableNormalCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|25:NewReplaceableNormalStage", replaceableNormalCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replaceable-normal (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|25:NewReplaceableNormalStage): %w", err))
		}
	}
	_ = replaceableNormal
	replaceableDefault, replaceableDefaultCleanup, err := func() (compositionfixture.ReplaceableStage, spicelifecycle.Cleanup, error) {
		if options.Overrides.Provider12.Enabled() {
			return options.Overrides.Provider12.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructReplaceableDefault_c1a89b56()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean replaceable-default (github.com/spice-framework/spice-agent/internal/compositionfixture.ReplaceableStage, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|26:NewReplaceableDefaultStage): %w", err))
	}
	if replaceableDefaultCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|26:NewReplaceableDefaultStage", replaceableDefaultCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean replaceable-default (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|26:NewReplaceableDefaultStage): %w", err))
		}
	}
	_ = replaceableDefault
	proof, proofCleanup, err := func() (*compositionfixture.Proof, spicelifecycle.Cleanup, error) {
		if options.Overrides.Proof.Enabled() {
			return options.Overrides.Proof.Acquire(ctx)
		}
		return spiceCompositionfixture.ConstructProof_7ff50430(beta, []compositionfixture.TextStage{trim, suffix}, fallbackOnly, replaceableNormal, map[string]compositionfixture.ToolAlias{"read": read, "write": write}, []stage.ToolDispatchGuard{fixtureDispatchGuard}, dispatchGuardLog, read, cleanup)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean proof (*github.com/spice-framework/spice-agent/internal/compositionfixture.Proof, source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|8:NewProof): %w", err))
	}
	if proofCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("github.com/spice-framework/spice-agent", "spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|8:NewProof", proofCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean proof (source spice:symbol:v1|function|66:github.com/spice-framework/spice-agent/internal/compositionfixture|0:|8:NewProof): %w", err))
		}
	}
	_ = proof
	return &applicationDependencies{
		trim:                 trim,
		cleanup:              cleanup,
		read:                 read,
		write:                write,
		suffix:               suffix,
		beta:                 beta,
		alpha:                alpha,
		dispatchGuardLog:     dispatchGuardLog,
		fallback:             fallback,
		fallbackOnly:         fallbackOnly,
		fixtureDispatchGuard: fixtureDispatchGuard,
		replaceableNormal:    replaceableNormal,
		replaceableDefault:   replaceableDefault,
		proof:                proof,
	}, nil
}
