//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	compositionfixture "github.com/spice-framework/spice-agent/internal/compositionfixture"
	spiceCompositionfixture "github.com/spice-framework/spice-agent/internal/spicegen/compositionproof/sources/internal_/compositionfixture"
	stage "github.com/spice-framework/spice-agent/stage"
	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

const TargetID = spiceCompositionfixture.ApplicationTargetCompositionProof_94ab0f70

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Trim is bean "trim".
	Trim compositionfixture.TextStage
	// Cleanup is bean "cleanup".
	Cleanup *compositionfixture.CleanupLog
	// Read is bean "read".
	Read compositionfixture.ToolAlias
	// Write is bean "write".
	Write compositionfixture.ToolAlias
	// Suffix is bean "suffix".
	Suffix compositionfixture.TextStage
	// Beta is bean "beta".
	Beta compositionfixture.ProviderAlias
	// Alpha is bean "alpha".
	Alpha compositionfixture.ProviderAlias
	// DispatchGuardLog is bean "dispatchGuardLog".
	DispatchGuardLog *compositionfixture.DispatchGuardLog
	// Fallback is bean "fallback".
	Fallback compositionfixture.ProviderAlias
	// Provider9 is bean "fallback-only".
	Provider9 compositionfixture.FallbackStage
	// FixtureDispatchGuard is bean "fixtureDispatchGuard".
	FixtureDispatchGuard stage.ToolDispatchGuard
	// Provider11 is bean "replaceable-normal".
	Provider11 compositionfixture.ReplaceableStage
	// Provider12 is bean "replaceable-default".
	Provider12 compositionfixture.ReplaceableStage
	// Proof is bean "proof".
	Proof *compositionfixture.Proof
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// Trim replaces bean "trim".
	Trim spicebean.Override[compositionfixture.TextStage]
	// Cleanup replaces bean "cleanup".
	Cleanup spicebean.Override[*compositionfixture.CleanupLog]
	// Read replaces bean "read".
	Read spicebean.Override[compositionfixture.ToolAlias]
	// Write replaces bean "write".
	Write spicebean.Override[compositionfixture.ToolAlias]
	// Suffix replaces bean "suffix".
	Suffix spicebean.Override[compositionfixture.TextStage]
	// Beta replaces bean "beta".
	Beta spicebean.Override[compositionfixture.ProviderAlias]
	// Alpha replaces bean "alpha".
	Alpha spicebean.Override[compositionfixture.ProviderAlias]
	// DispatchGuardLog replaces bean "dispatchGuardLog".
	DispatchGuardLog spicebean.Override[*compositionfixture.DispatchGuardLog]
	// Fallback replaces bean "fallback".
	Fallback spicebean.Override[compositionfixture.ProviderAlias]
	// Provider9 replaces bean "fallback-only".
	Provider9 spicebean.Override[compositionfixture.FallbackStage]
	// FixtureDispatchGuard replaces bean "fixtureDispatchGuard".
	FixtureDispatchGuard spicebean.Override[stage.ToolDispatchGuard]
	// Provider11 replaces bean "replaceable-normal".
	Provider11 spicebean.Override[compositionfixture.ReplaceableStage]
	// Provider12 replaces bean "replaceable-default".
	Provider12 spicebean.Override[compositionfixture.ReplaceableStage]
	// Proof replaces bean "proof".
	Proof spicebean.Override[*compositionfixture.Proof]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.Trim.Enabled() {
			result.Trim = layer.Overrides.Trim
		}
		if layer.Overrides.Cleanup.Enabled() {
			result.Cleanup = layer.Overrides.Cleanup
		}
		if layer.Overrides.Read.Enabled() {
			result.Read = layer.Overrides.Read
		}
		if layer.Overrides.Write.Enabled() {
			result.Write = layer.Overrides.Write
		}
		if layer.Overrides.Suffix.Enabled() {
			result.Suffix = layer.Overrides.Suffix
		}
		if layer.Overrides.Beta.Enabled() {
			result.Beta = layer.Overrides.Beta
		}
		if layer.Overrides.Alpha.Enabled() {
			result.Alpha = layer.Overrides.Alpha
		}
		if layer.Overrides.DispatchGuardLog.Enabled() {
			result.DispatchGuardLog = layer.Overrides.DispatchGuardLog
		}
		if layer.Overrides.Fallback.Enabled() {
			result.Fallback = layer.Overrides.Fallback
		}
		if layer.Overrides.Provider9.Enabled() {
			result.Provider9 = layer.Overrides.Provider9
		}
		if layer.Overrides.FixtureDispatchGuard.Enabled() {
			result.FixtureDispatchGuard = layer.Overrides.FixtureDispatchGuard
		}
		if layer.Overrides.Provider11.Enabled() {
			result.Provider11 = layer.Overrides.Provider11
		}
		if layer.Overrides.Provider12.Enabled() {
			result.Provider12 = layer.Overrides.Provider12
		}
		if layer.Overrides.Proof.Enabled() {
			result.Proof = layer.Overrides.Proof
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
