# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spice.agent.plugin.v1 import plugin_pb2 as spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spice/agent/plugin/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub(object):
    """PluginService is the initial runtime-tool-only local process boundary.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/spice.agent.plugin.v1.PluginService/Initialize',
                request_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeRequest.SerializeToString,
                response_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/spice.agent.plugin.v1.PluginService/Execute',
                request_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/spice.agent.plugin.v1.PluginService/Drain',
                request_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainRequest.SerializeToString,
                response_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/spice.agent.plugin.v1.PluginService/Shutdown',
                request_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class PluginServiceServicer(object):
    """PluginService is the initial runtime-tool-only local process boundary.
    """

    def Initialize(self, request, context):
        """Initialize authenticates and freezes one candidate connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute streams progress and one terminal frame unless transport
        cancellation preempts normal completion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Drain stops admission and joins admitted calls.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown releases a drained candidate.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeRequest.FromString,
                    response_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteRequest.FromString,
                    response_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteResponse.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainRequest.FromString,
                    response_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.FromString,
                    response_serializer=spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spice.agent.plugin.v1.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spice.agent.plugin.v1.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """PluginService is the initial runtime-tool-only local process boundary.
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spice.agent.plugin.v1.PluginService/Initialize',
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeRequest.SerializeToString,
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spice.agent.plugin.v1.PluginService/Execute',
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteRequest.SerializeToString,
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spice.agent.plugin.v1.PluginService/Drain',
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainRequest.SerializeToString,
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.DrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spice.agent.plugin.v1.PluginService/Shutdown',
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownRequest.SerializeToString,
            spice_dot_agent_dot_plugin_dot_v1_dot_plugin__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
