// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: spice/agent/engine/v1/engine.proto

package enginev1

import (
	v1 "github.com/spice-framework/spice-agent/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageRole identifies a provider-neutral conversation author.
type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_SYSTEM      MessageRole = 1
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 2
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 3
	MessageRole_MESSAGE_ROLE_TOOL        MessageRole = 4
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_SYSTEM",
		2: "MESSAGE_ROLE_USER",
		3: "MESSAGE_ROLE_ASSISTANT",
		4: "MESSAGE_ROLE_TOOL",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_SYSTEM":      1,
		"MESSAGE_ROLE_USER":        2,
		"MESSAGE_ROLE_ASSISTANT":   3,
		"MESSAGE_ROLE_TOOL":        4,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_spice_agent_engine_v1_engine_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_spice_agent_engine_v1_engine_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

// EventKind identifies one stable engine event.
type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED           EventKind = 0
	EventKind_EVENT_KIND_RUN_STARTED           EventKind = 1
	EventKind_EVENT_KIND_RUN_COMPLETED         EventKind = 2
	EventKind_EVENT_KIND_RUN_FAILED            EventKind = 3
	EventKind_EVENT_KIND_RUN_CANCELLED         EventKind = 4
	EventKind_EVENT_KIND_TURN_STARTED          EventKind = 5
	EventKind_EVENT_KIND_TURN_COMPLETED        EventKind = 6
	EventKind_EVENT_KIND_TURN_FAILED           EventKind = 7
	EventKind_EVENT_KIND_MODEL_STARTED         EventKind = 8
	EventKind_EVENT_KIND_MODEL_DELTA           EventKind = 9
	EventKind_EVENT_KIND_MODEL_COMPLETED       EventKind = 10
	EventKind_EVENT_KIND_MODEL_FAILED          EventKind = 11
	EventKind_EVENT_KIND_TOOL_STARTED          EventKind = 12
	EventKind_EVENT_KIND_TOOL_PROGRESS         EventKind = 13
	EventKind_EVENT_KIND_TOOL_COMPLETED        EventKind = 14
	EventKind_EVENT_KIND_TOOL_FAILED           EventKind = 15
	EventKind_EVENT_KIND_INTERACTION_STARTED   EventKind = 16
	EventKind_EVENT_KIND_INTERACTION_COMPLETED EventKind = 17
	EventKind_EVENT_KIND_INTERACTION_FAILED    EventKind = 18
	EventKind_EVENT_KIND_INTERACTION_CANCELLED EventKind = 19
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0:  "EVENT_KIND_UNSPECIFIED",
		1:  "EVENT_KIND_RUN_STARTED",
		2:  "EVENT_KIND_RUN_COMPLETED",
		3:  "EVENT_KIND_RUN_FAILED",
		4:  "EVENT_KIND_RUN_CANCELLED",
		5:  "EVENT_KIND_TURN_STARTED",
		6:  "EVENT_KIND_TURN_COMPLETED",
		7:  "EVENT_KIND_TURN_FAILED",
		8:  "EVENT_KIND_MODEL_STARTED",
		9:  "EVENT_KIND_MODEL_DELTA",
		10: "EVENT_KIND_MODEL_COMPLETED",
		11: "EVENT_KIND_MODEL_FAILED",
		12: "EVENT_KIND_TOOL_STARTED",
		13: "EVENT_KIND_TOOL_PROGRESS",
		14: "EVENT_KIND_TOOL_COMPLETED",
		15: "EVENT_KIND_TOOL_FAILED",
		16: "EVENT_KIND_INTERACTION_STARTED",
		17: "EVENT_KIND_INTERACTION_COMPLETED",
		18: "EVENT_KIND_INTERACTION_FAILED",
		19: "EVENT_KIND_INTERACTION_CANCELLED",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED":           0,
		"EVENT_KIND_RUN_STARTED":           1,
		"EVENT_KIND_RUN_COMPLETED":         2,
		"EVENT_KIND_RUN_FAILED":            3,
		"EVENT_KIND_RUN_CANCELLED":         4,
		"EVENT_KIND_TURN_STARTED":          5,
		"EVENT_KIND_TURN_COMPLETED":        6,
		"EVENT_KIND_TURN_FAILED":           7,
		"EVENT_KIND_MODEL_STARTED":         8,
		"EVENT_KIND_MODEL_DELTA":           9,
		"EVENT_KIND_MODEL_COMPLETED":       10,
		"EVENT_KIND_MODEL_FAILED":          11,
		"EVENT_KIND_TOOL_STARTED":          12,
		"EVENT_KIND_TOOL_PROGRESS":         13,
		"EVENT_KIND_TOOL_COMPLETED":        14,
		"EVENT_KIND_TOOL_FAILED":           15,
		"EVENT_KIND_INTERACTION_STARTED":   16,
		"EVENT_KIND_INTERACTION_COMPLETED": 17,
		"EVENT_KIND_INTERACTION_FAILED":    18,
		"EVENT_KIND_INTERACTION_CANCELLED": 19,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_spice_agent_engine_v1_engine_proto_enumTypes[1].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_spice_agent_engine_v1_engine_proto_enumTypes[1]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

// SnapshotLifecycle is a safe export/import boundary.
type SnapshotLifecycle int32

const (
	SnapshotLifecycle_SNAPSHOT_LIFECYCLE_UNSPECIFIED SnapshotLifecycle = 0
	SnapshotLifecycle_SNAPSHOT_LIFECYCLE_SUSPENDED   SnapshotLifecycle = 1
	SnapshotLifecycle_SNAPSHOT_LIFECYCLE_COMPLETED   SnapshotLifecycle = 2
	SnapshotLifecycle_SNAPSHOT_LIFECYCLE_FAILED      SnapshotLifecycle = 3
	SnapshotLifecycle_SNAPSHOT_LIFECYCLE_CANCELLED   SnapshotLifecycle = 4
)

// Enum value maps for SnapshotLifecycle.
var (
	SnapshotLifecycle_name = map[int32]string{
		0: "SNAPSHOT_LIFECYCLE_UNSPECIFIED",
		1: "SNAPSHOT_LIFECYCLE_SUSPENDED",
		2: "SNAPSHOT_LIFECYCLE_COMPLETED",
		3: "SNAPSHOT_LIFECYCLE_FAILED",
		4: "SNAPSHOT_LIFECYCLE_CANCELLED",
	}
	SnapshotLifecycle_value = map[string]int32{
		"SNAPSHOT_LIFECYCLE_UNSPECIFIED": 0,
		"SNAPSHOT_LIFECYCLE_SUSPENDED":   1,
		"SNAPSHOT_LIFECYCLE_COMPLETED":   2,
		"SNAPSHOT_LIFECYCLE_FAILED":      3,
		"SNAPSHOT_LIFECYCLE_CANCELLED":   4,
	}
)

func (x SnapshotLifecycle) Enum() *SnapshotLifecycle {
	p := new(SnapshotLifecycle)
	*p = x
	return p
}

func (x SnapshotLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_spice_agent_engine_v1_engine_proto_enumTypes[2].Descriptor()
}

func (SnapshotLifecycle) Type() protoreflect.EnumType {
	return &file_spice_agent_engine_v1_engine_proto_enumTypes[2]
}

func (x SnapshotLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotLifecycle.Descriptor instead.
func (SnapshotLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

// ToolCallPart is a bounded model-requested tool invocation.
type ToolCallPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ArgumentsJson []byte                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallPart) Reset() {
	*x = ToolCallPart{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallPart) ProtoMessage() {}

func (x *ToolCallPart) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallPart.ProtoReflect.Descriptor instead.
func (*ToolCallPart) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ToolCallPart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCallPart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallPart) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

// ToolResultPart is a bounded tool result correlated to one call.
type ToolResultPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultPart) Reset() {
	*x = ToolResultPart{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultPart) ProtoMessage() {}

func (x *ToolResultPart) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultPart.ProtoReflect.Descriptor instead.
func (*ToolResultPart) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ToolResultPart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResultPart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolResultPart) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

// ExtensionPart is portable namespaced JSON content.
type ExtensionPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ValueJson     []byte                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionPart) Reset() {
	*x = ExtensionPart{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionPart) ProtoMessage() {}

func (x *ExtensionPart) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionPart.ProtoReflect.Descriptor instead.
func (*ExtensionPart) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ExtensionPart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExtensionPart) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

// ContentPart contains exactly one provider-neutral message payload.
type ContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ContentPart_Text
	//	*ContentPart_ToolCall
	//	*ContentPart_ToolResult
	//	*ContentPart_Extension
	Value         isContentPart_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentPart) Reset() {
	*x = ContentPart{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPart) ProtoMessage() {}

func (x *ContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPart.ProtoReflect.Descriptor instead.
func (*ContentPart) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ContentPart) GetValue() isContentPart_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ContentPart) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*ContentPart_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ContentPart) GetToolCall() *ToolCallPart {
	if x != nil {
		if x, ok := x.Value.(*ContentPart_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *ContentPart) GetToolResult() *ToolResultPart {
	if x != nil {
		if x, ok := x.Value.(*ContentPart_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *ContentPart) GetExtension() *ExtensionPart {
	if x != nil {
		if x, ok := x.Value.(*ContentPart_Extension); ok {
			return x.Extension
		}
	}
	return nil
}

type isContentPart_Value interface {
	isContentPart_Value()
}

type ContentPart_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentPart_ToolCall struct {
	ToolCall *ToolCallPart `protobuf:"bytes,2,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type ContentPart_ToolResult struct {
	ToolResult *ToolResultPart `protobuf:"bytes,3,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type ContentPart_Extension struct {
	Extension *ExtensionPart `protobuf:"bytes,4,opt,name=extension,proto3,oneof"`
}

func (*ContentPart_Text) isContentPart_Value() {}

func (*ContentPart_ToolCall) isContentPart_Value() {}

func (*ContentPart_ToolResult) isContentPart_Value() {}

func (*ContentPart_Extension) isContentPart_Value() {}

// Message is one bounded provider-neutral conversation entry.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          MessageRole            `protobuf:"varint,2,opt,name=role,proto3,enum=spice.agent.engine.v1.MessageRole" json:"role,omitempty"`
	Parts         []*ContentPart         `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetParts() []*ContentPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

// AgentDefinitionRef identifies a validated generated execution definition.
type AgentDefinitionRef struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Revision string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Model    string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxTurns uint32                 `protobuf:"varint,4,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	// expected_static_plan_fingerprint is an assertion, not client authority.
	ExpectedStaticPlanFingerprint string `protobuf:"bytes,5,opt,name=expected_static_plan_fingerprint,json=expectedStaticPlanFingerprint,proto3" json:"expected_static_plan_fingerprint,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AgentDefinitionRef) Reset() {
	*x = AgentDefinitionRef{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDefinitionRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDefinitionRef) ProtoMessage() {}

func (x *AgentDefinitionRef) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDefinitionRef.ProtoReflect.Descriptor instead.
func (*AgentDefinitionRef) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *AgentDefinitionRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentDefinitionRef) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *AgentDefinitionRef) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentDefinitionRef) GetMaxTurns() uint32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *AgentDefinitionRef) GetExpectedStaticPlanFingerprint() string {
	if x != nil {
		return x.ExpectedStaticPlanFingerprint
	}
	return ""
}

// InitializeRequest is the mandatory first authenticated client operation.
type InitializeRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Protocol              *v1.ProtocolRange      `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Client                *v1.BuildIdentity      `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	SupportedCapabilities *v1.CapabilitySet      `protobuf:"bytes,3,opt,name=supported_capabilities,json=supportedCapabilities,proto3" json:"supported_capabilities,omitempty"`
	RequiredCapabilities  *v1.CapabilitySet      `protobuf:"bytes,4,opt,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	RequestedLimits       *v1.Limits             `protobuf:"bytes,5,opt,name=requested_limits,json=requestedLimits,proto3" json:"requested_limits,omitempty"`
	AuthenticationToken   []byte                 `protobuf:"bytes,6,opt,name=authentication_token,json=authenticationToken,proto3" json:"authentication_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *InitializeRequest) GetProtocol() *v1.ProtocolRange {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *InitializeRequest) GetClient() *v1.BuildIdentity {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *InitializeRequest) GetSupportedCapabilities() *v1.CapabilitySet {
	if x != nil {
		return x.SupportedCapabilities
	}
	return nil
}

func (x *InitializeRequest) GetRequiredCapabilities() *v1.CapabilitySet {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *InitializeRequest) GetRequestedLimits() *v1.Limits {
	if x != nil {
		return x.RequestedLimits
	}
	return nil
}

func (x *InitializeRequest) GetAuthenticationToken() []byte {
	if x != nil {
		return x.AuthenticationToken
	}
	return nil
}

// InitializeResponse contains the negotiated connection contract.
type InitializeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Protocol       *v1.ProtocolVersion    `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Server         *v1.BuildIdentity      `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Capabilities   *v1.CapabilitySet      `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Limits         *v1.Limits             `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	Health         *v1.Health             `protobuf:"bytes,6,opt,name=health,proto3" json:"health,omitempty"`
	ClientId       string                 `protobuf:"bytes,7,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch uint64                 `protobuf:"varint,8,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *InitializeResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InitializeResponse) GetProtocol() *v1.ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *InitializeResponse) GetServer() *v1.BuildIdentity {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *InitializeResponse) GetCapabilities() *v1.CapabilitySet {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *InitializeResponse) GetLimits() *v1.Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *InitializeResponse) GetHealth() *v1.Health {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *InitializeResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *InitializeResponse) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

// HealthRequest identifies the initialized client.
type HealthRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *HealthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HealthRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

// HealthResponse reports bounded readiness and limits.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Server        *v1.BuildIdentity      `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Protocol      *v1.ProtocolVersion    `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Health        *v1.Health             `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HealthResponse) GetServer() *v1.BuildIdentity {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *HealthResponse) GetProtocol() *v1.ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *HealthResponse) GetHealth() *v1.Health {
	if x != nil {
		return x.Health
	}
	return nil
}

// StartRunRequest creates one run exactly once per client operation ID.
type StartRunRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientId          string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch    uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	ClientOperationId string                 `protobuf:"bytes,3,opt,name=client_operation_id,json=clientOperationId,proto3" json:"client_operation_id,omitempty"`
	Definition        *AgentDefinitionRef    `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	Input             *Message               `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{10}
}

func (x *StartRunRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StartRunRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *StartRunRequest) GetClientOperationId() string {
	if x != nil {
		return x.ClientOperationId
	}
	return ""
}

func (x *StartRunRequest) GetDefinition() *AgentDefinitionRef {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *StartRunRequest) GetInput() *Message {
	if x != nil {
		return x.Input
	}
	return nil
}

// StartRunResponse returns the stable run identity and first sequence.
type StartRunResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RunId              string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	InitialSequence    uint64                 `protobuf:"varint,3,opt,name=initial_sequence,json=initialSequence,proto3" json:"initial_sequence,omitempty"`
	DuplicateOperation bool                   `protobuf:"varint,4,opt,name=duplicate_operation,json=duplicateOperation,proto3" json:"duplicate_operation,omitempty"`
	// plan_id authoritatively identifies the server-selected immutable plan.
	PlanId        string `protobuf:"bytes,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{11}
}

func (x *StartRunResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StartRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartRunResponse) GetInitialSequence() uint64 {
	if x != nil {
		return x.InitialSequence
	}
	return 0
}

func (x *StartRunResponse) GetDuplicateOperation() bool {
	if x != nil {
		return x.DuplicateOperation
	}
	return false
}

func (x *StartRunResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

// StreamEventsRequest replays and tails events after an acknowledged sequence.
type StreamEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AfterSequence  uint64                 `protobuf:"varint,4,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	ReplayLimit    uint32                 `protobuf:"varint,5,opt,name=replay_limit,json=replayLimit,proto3" json:"replay_limit,omitempty"`
	Tail           bool                   `protobuf:"varint,6,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{12}
}

func (x *StreamEventsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamEventsRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *StreamEventsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StreamEventsRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *StreamEventsRequest) GetReplayLimit() uint32 {
	if x != nil {
		return x.ReplayLimit
	}
	return 0
}

func (x *StreamEventsRequest) GetTail() bool {
	if x != nil {
		return x.Tail
	}
	return false
}

// RunEvent is one strictly increasing authoritative event envelope.
type RunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	UnixNano      int64                  `protobuf:"varint,3,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	Kind          EventKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=spice.agent.engine.v1.EventKind" json:"kind,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Terminal      bool                   `protobuf:"varint,6,opt,name=terminal,proto3" json:"terminal,omitempty"`
	OperationId   string                 `protobuf:"bytes,7,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{13}
}

func (x *RunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RunEvent) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

func (x *RunEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *RunEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *RunEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *RunEvent) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// StreamControl marks replay bounds, terminal status, or disconnect position.
type StreamControl struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EarliestSequence      uint64                 `protobuf:"varint,2,opt,name=earliest_sequence,json=earliestSequence,proto3" json:"earliest_sequence,omitempty"`
	LatestSequence        uint64                 `protobuf:"varint,3,opt,name=latest_sequence,json=latestSequence,proto3" json:"latest_sequence,omitempty"`
	LastDeliveredSequence uint64                 `protobuf:"varint,4,opt,name=last_delivered_sequence,json=lastDeliveredSequence,proto3" json:"last_delivered_sequence,omitempty"`
	Tailing               bool                   `protobuf:"varint,5,opt,name=tailing,proto3" json:"tailing,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamControl) Reset() {
	*x = StreamControl{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControl) ProtoMessage() {}

func (x *StreamControl) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControl.ProtoReflect.Descriptor instead.
func (*StreamControl) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{14}
}

func (x *StreamControl) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StreamControl) GetEarliestSequence() uint64 {
	if x != nil {
		return x.EarliestSequence
	}
	return 0
}

func (x *StreamControl) GetLatestSequence() uint64 {
	if x != nil {
		return x.LatestSequence
	}
	return 0
}

func (x *StreamControl) GetLastDeliveredSequence() uint64 {
	if x != nil {
		return x.LastDeliveredSequence
	}
	return 0
}

func (x *StreamControl) GetTailing() bool {
	if x != nil {
		return x.Tailing
	}
	return false
}

// StreamEventsResponse contains one event or one explicit control record.
type StreamEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamEventsResponse_Event
	//	*StreamEventsResponse_Control
	Payload       isStreamEventsResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{15}
}

func (x *StreamEventsResponse) GetPayload() isStreamEventsResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamEventsResponse) GetEvent() *RunEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamEventsResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *StreamEventsResponse) GetControl() *StreamControl {
	if x != nil {
		if x, ok := x.Payload.(*StreamEventsResponse_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isStreamEventsResponse_Payload interface {
	isStreamEventsResponse_Payload()
}

type StreamEventsResponse_Event struct {
	Event *RunEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type StreamEventsResponse_Control struct {
	Control *StreamControl `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*StreamEventsResponse_Event) isStreamEventsResponse_Payload() {}

func (*StreamEventsResponse_Control) isStreamEventsResponse_Payload() {}

// CancelRunRequest idempotently asks the engine to cancel one run.
type CancelRunRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientId          string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch    uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	ClientOperationId string                 `protobuf:"bytes,3,opt,name=client_operation_id,json=clientOperationId,proto3" json:"client_operation_id,omitempty"`
	RunId             string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{16}
}

func (x *CancelRunRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CancelRunRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *CancelRunRequest) GetClientOperationId() string {
	if x != nil {
		return x.ClientOperationId
	}
	return ""
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CancelRunRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelRunResponse distinguishes new cancellation from an existing terminal.
type CancelRunResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CancellationRequested bool                   `protobuf:"varint,2,opt,name=cancellation_requested,json=cancellationRequested,proto3" json:"cancellation_requested,omitempty"`
	AlreadyTerminal       bool                   `protobuf:"varint,3,opt,name=already_terminal,json=alreadyTerminal,proto3" json:"already_terminal,omitempty"`
	TerminalSequence      uint64                 `protobuf:"varint,4,opt,name=terminal_sequence,json=terminalSequence,proto3" json:"terminal_sequence,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{17}
}

func (x *CancelRunResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CancelRunResponse) GetCancellationRequested() bool {
	if x != nil {
		return x.CancellationRequested
	}
	return false
}

func (x *CancelRunResponse) GetAlreadyTerminal() bool {
	if x != nil {
		return x.AlreadyTerminal
	}
	return false
}

func (x *CancelRunResponse) GetTerminalSequence() uint64 {
	if x != nil {
		return x.TerminalSequence
	}
	return 0
}

// RespondInteractionRequest completes one pending interaction exactly once.
type RespondInteractionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientId          string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch    uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	ClientOperationId string                 `protobuf:"bytes,3,opt,name=client_operation_id,json=clientOperationId,proto3" json:"client_operation_id,omitempty"`
	RunId             string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	InteractionId     string                 `protobuf:"bytes,5,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	ResponseId        string                 `protobuf:"bytes,6,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	ValueJson         []byte                 `protobuf:"bytes,7,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RespondInteractionRequest) Reset() {
	*x = RespondInteractionRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondInteractionRequest) ProtoMessage() {}

func (x *RespondInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondInteractionRequest.ProtoReflect.Descriptor instead.
func (*RespondInteractionRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{18}
}

func (x *RespondInteractionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RespondInteractionRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *RespondInteractionRequest) GetClientOperationId() string {
	if x != nil {
		return x.ClientOperationId
	}
	return ""
}

func (x *RespondInteractionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RespondInteractionRequest) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *RespondInteractionRequest) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *RespondInteractionRequest) GetValueJson() []byte {
	if x != nil {
		return x.ValueJson
	}
	return nil
}

// RespondInteractionResponse reports duplicate and committed responses.
type RespondInteractionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Accepted          bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DuplicateResponse bool                   `protobuf:"varint,3,opt,name=duplicate_response,json=duplicateResponse,proto3" json:"duplicate_response,omitempty"`
	CommittedSequence uint64                 `protobuf:"varint,4,opt,name=committed_sequence,json=committedSequence,proto3" json:"committed_sequence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RespondInteractionResponse) Reset() {
	*x = RespondInteractionResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondInteractionResponse) ProtoMessage() {}

func (x *RespondInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondInteractionResponse.ProtoReflect.Descriptor instead.
func (*RespondInteractionResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{19}
}

func (x *RespondInteractionResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RespondInteractionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RespondInteractionResponse) GetDuplicateResponse() bool {
	if x != nil {
		return x.DuplicateResponse
	}
	return false
}

func (x *RespondInteractionResponse) GetCommittedSequence() uint64 {
	if x != nil {
		return x.CommittedSequence
	}
	return 0
}

// SnapshotEnvelope carries one checksummed provider-neutral safe snapshot.
type SnapshotEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	LastSequence  uint64                 `protobuf:"varint,3,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	Lifecycle     SnapshotLifecycle      `protobuf:"varint,4,opt,name=lifecycle,proto3,enum=spice.agent.engine.v1.SnapshotLifecycle" json:"lifecycle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEnvelope) Reset() {
	*x = SnapshotEnvelope{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnvelope) ProtoMessage() {}

func (x *SnapshotEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnvelope.ProtoReflect.Descriptor instead.
func (*SnapshotEnvelope) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{20}
}

func (x *SnapshotEnvelope) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SnapshotEnvelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SnapshotEnvelope) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

func (x *SnapshotEnvelope) GetLifecycle() SnapshotLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return SnapshotLifecycle_SNAPSHOT_LIFECYCLE_UNSPECIFIED
}

func (x *SnapshotEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SnapshotEnvelope) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// ExportSnapshotRequest requests a safe completed-turn or terminal boundary.
type ExportSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportSnapshotRequest) Reset() {
	*x = ExportSnapshotRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotRequest) ProtoMessage() {}

func (x *ExportSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ExportSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{21}
}

func (x *ExportSnapshotRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ExportSnapshotRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *ExportSnapshotRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// ExportSnapshotResponse contains the safe snapshot or typed refusal.
type ExportSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Snapshot      *SnapshotEnvelope      `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSnapshotResponse) Reset() {
	*x = ExportSnapshotResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotResponse) ProtoMessage() {}

func (x *ExportSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ExportSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{22}
}

func (x *ExportSnapshotResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExportSnapshotResponse) GetSnapshot() *SnapshotEnvelope {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// ImportSnapshotRequest resumes a suspended snapshot with explicit ownership.
type ImportSnapshotRequest struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	ClientId                      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OwnershipEpoch                uint64                 `protobuf:"varint,2,opt,name=ownership_epoch,json=ownershipEpoch,proto3" json:"ownership_epoch,omitempty"`
	ClientOperationId             string                 `protobuf:"bytes,3,opt,name=client_operation_id,json=clientOperationId,proto3" json:"client_operation_id,omitempty"`
	NewRunId                      string                 `protobuf:"bytes,4,opt,name=new_run_id,json=newRunId,proto3" json:"new_run_id,omitempty"`
	ExpectedStaticPlanFingerprint string                 `protobuf:"bytes,5,opt,name=expected_static_plan_fingerprint,json=expectedStaticPlanFingerprint,proto3" json:"expected_static_plan_fingerprint,omitempty"`
	ExpectedPlanId                string                 `protobuf:"bytes,6,opt,name=expected_plan_id,json=expectedPlanId,proto3" json:"expected_plan_id,omitempty"`
	Snapshot                      *SnapshotEnvelope      `protobuf:"bytes,7,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ImportSnapshotRequest) Reset() {
	*x = ImportSnapshotRequest{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSnapshotRequest) ProtoMessage() {}

func (x *ImportSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ImportSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{23}
}

func (x *ImportSnapshotRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ImportSnapshotRequest) GetOwnershipEpoch() uint64 {
	if x != nil {
		return x.OwnershipEpoch
	}
	return 0
}

func (x *ImportSnapshotRequest) GetClientOperationId() string {
	if x != nil {
		return x.ClientOperationId
	}
	return ""
}

func (x *ImportSnapshotRequest) GetNewRunId() string {
	if x != nil {
		return x.NewRunId
	}
	return ""
}

func (x *ImportSnapshotRequest) GetExpectedStaticPlanFingerprint() string {
	if x != nil {
		return x.ExpectedStaticPlanFingerprint
	}
	return ""
}

func (x *ImportSnapshotRequest) GetExpectedPlanId() string {
	if x != nil {
		return x.ExpectedPlanId
	}
	return ""
}

func (x *ImportSnapshotRequest) GetSnapshot() *SnapshotEnvelope {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// ImportSnapshotResponse returns the imported run and continuation sequence.
type ImportSnapshotResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             *v1.Status             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RunId              string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	NextSequence       uint64                 `protobuf:"varint,3,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	DuplicateOperation bool                   `protobuf:"varint,4,opt,name=duplicate_operation,json=duplicateOperation,proto3" json:"duplicate_operation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ImportSnapshotResponse) Reset() {
	*x = ImportSnapshotResponse{}
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSnapshotResponse) ProtoMessage() {}

func (x *ImportSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spice_agent_engine_v1_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSnapshotResponse.ProtoReflect.Descriptor instead.
func (*ImportSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_spice_agent_engine_v1_engine_proto_rawDescGZIP(), []int{24}
}

func (x *ImportSnapshotResponse) GetStatus() *v1.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ImportSnapshotResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ImportSnapshotResponse) GetNextSequence() uint64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

func (x *ImportSnapshotResponse) GetDuplicateOperation() bool {
	if x != nil {
		return x.DuplicateOperation
	}
	return false
}

var File_spice_agent_engine_v1_engine_proto protoreflect.FileDescriptor

const file_spice_agent_engine_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\"spice/agent/engine/v1/engine.proto\x12\x15spice.agent.engine.v1\x1a\"spice/agent/common/v1/common.proto\"b\n" +
	"\fToolCallPart\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\fR\rargumentsJson\"^\n" +
	"\x0eToolResultPart\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"L\n" +
	"\rExtensionPart\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\fR\tvalueJson\"\x80\x02\n" +
	"\vContentPart\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12B\n" +
	"\ttool_call\x18\x02 \x01(\v2#.spice.agent.engine.v1.ToolCallPartH\x00R\btoolCall\x12H\n" +
	"\vtool_result\x18\x03 \x01(\v2%.spice.agent.engine.v1.ToolResultPartH\x00R\n" +
	"toolResult\x12D\n" +
	"\textension\x18\x04 \x01(\v2$.spice.agent.engine.v1.ExtensionPartH\x00R\textensionB\a\n" +
	"\x05value\"\x8b\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x04role\x18\x02 \x01(\x0e2\".spice.agent.engine.v1.MessageRoleR\x04role\x128\n" +
	"\x05parts\x18\x03 \x03(\v2\".spice.agent.engine.v1.ContentPartR\x05parts\"\xc2\x01\n" +
	"\x12AgentDefinitionRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1b\n" +
	"\tmax_turns\x18\x04 \x01(\rR\bmaxTurns\x12G\n" +
	" expected_static_plan_fingerprint\x18\x05 \x01(\tR\x1dexpectedStaticPlanFingerprintJ\x04\b\x06\x10\a\"\xc8\x03\n" +
	"\x11InitializeRequest\x12@\n" +
	"\bprotocol\x18\x01 \x01(\v2$.spice.agent.common.v1.ProtocolRangeR\bprotocol\x12<\n" +
	"\x06client\x18\x02 \x01(\v2$.spice.agent.common.v1.BuildIdentityR\x06client\x12[\n" +
	"\x16supported_capabilities\x18\x03 \x01(\v2$.spice.agent.common.v1.CapabilitySetR\x15supportedCapabilities\x12Y\n" +
	"\x15required_capabilities\x18\x04 \x01(\v2$.spice.agent.common.v1.CapabilitySetR\x14requiredCapabilities\x12H\n" +
	"\x10requested_limits\x18\x05 \x01(\v2\x1d.spice.agent.common.v1.LimitsR\x0frequestedLimits\x121\n" +
	"\x14authentication_token\x18\x06 \x01(\fR\x13authenticationToken\"\xcb\x03\n" +
	"\x12InitializeResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12B\n" +
	"\bprotocol\x18\x02 \x01(\v2&.spice.agent.common.v1.ProtocolVersionR\bprotocol\x12<\n" +
	"\x06server\x18\x03 \x01(\v2$.spice.agent.common.v1.BuildIdentityR\x06server\x12H\n" +
	"\fcapabilities\x18\x04 \x01(\v2$.spice.agent.common.v1.CapabilitySetR\fcapabilities\x125\n" +
	"\x06limits\x18\x05 \x01(\v2\x1d.spice.agent.common.v1.LimitsR\x06limits\x125\n" +
	"\x06health\x18\x06 \x01(\v2\x1d.spice.agent.common.v1.HealthR\x06health\x12\x1b\n" +
	"\tclient_id\x18\a \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\b \x01(\x04R\x0eownershipEpoch\"U\n" +
	"\rHealthRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\"\x80\x02\n" +
	"\x0eHealthResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12<\n" +
	"\x06server\x18\x02 \x01(\v2$.spice.agent.common.v1.BuildIdentityR\x06server\x12B\n" +
	"\bprotocol\x18\x03 \x01(\v2&.spice.agent.common.v1.ProtocolVersionR\bprotocol\x125\n" +
	"\x06health\x18\x04 \x01(\v2\x1d.spice.agent.common.v1.HealthR\x06health\"\x88\x02\n" +
	"\x0fStartRunRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12.\n" +
	"\x13client_operation_id\x18\x03 \x01(\tR\x11clientOperationId\x12I\n" +
	"\n" +
	"definition\x18\x04 \x01(\v2).spice.agent.engine.v1.AgentDefinitionRefR\n" +
	"definition\x124\n" +
	"\x05input\x18\x05 \x01(\v2\x1e.spice.agent.engine.v1.MessageR\x05input\"\xd5\x01\n" +
	"\x10StartRunResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12)\n" +
	"\x10initial_sequence\x18\x03 \x01(\x04R\x0finitialSequence\x12/\n" +
	"\x13duplicate_operation\x18\x04 \x01(\bR\x12duplicateOperation\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\tR\x06planId\"\xd0\x01\n" +
	"\x13StreamEventsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12%\n" +
	"\x0eafter_sequence\x18\x04 \x01(\x04R\rafterSequence\x12!\n" +
	"\freplay_limit\x18\x05 \x01(\rR\vreplayLimit\x12\x12\n" +
	"\x04tail\x18\x06 \x01(\bR\x04tail\"\xf2\x01\n" +
	"\bRunEvent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tunix_nano\x18\x03 \x01(\x03R\bunixNano\x124\n" +
	"\x04kind\x18\x04 \x01(\x0e2 .spice.agent.engine.v1.EventKindR\x04kind\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJson\x12\x1a\n" +
	"\bterminal\x18\x06 \x01(\bR\bterminal\x12!\n" +
	"\foperation_id\x18\a \x01(\tR\voperationId\"\xee\x01\n" +
	"\rStreamControl\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12+\n" +
	"\x11earliest_sequence\x18\x02 \x01(\x04R\x10earliestSequence\x12'\n" +
	"\x0flatest_sequence\x18\x03 \x01(\x04R\x0elatestSequence\x126\n" +
	"\x17last_delivered_sequence\x18\x04 \x01(\x04R\x15lastDeliveredSequence\x12\x18\n" +
	"\atailing\x18\x05 \x01(\bR\atailing\"\x9c\x01\n" +
	"\x14StreamEventsResponse\x127\n" +
	"\x05event\x18\x01 \x01(\v2\x1f.spice.agent.engine.v1.RunEventH\x00R\x05event\x12@\n" +
	"\acontrol\x18\x02 \x01(\v2$.spice.agent.engine.v1.StreamControlH\x00R\acontrolB\t\n" +
	"\apayload\"\xb7\x01\n" +
	"\x10CancelRunRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12.\n" +
	"\x13client_operation_id\x18\x03 \x01(\tR\x11clientOperationId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xd9\x01\n" +
	"\x11CancelRunResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x125\n" +
	"\x16cancellation_requested\x18\x02 \x01(\bR\x15cancellationRequested\x12)\n" +
	"\x10already_terminal\x18\x03 \x01(\bR\x0falreadyTerminal\x12+\n" +
	"\x11terminal_sequence\x18\x04 \x01(\x04R\x10terminalSequence\"\x8f\x02\n" +
	"\x19RespondInteractionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12.\n" +
	"\x13client_operation_id\x18\x03 \x01(\tR\x11clientOperationId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12%\n" +
	"\x0einteraction_id\x18\x05 \x01(\tR\rinteractionId\x12\x1f\n" +
	"\vresponse_id\x18\x06 \x01(\tR\n" +
	"responseId\x12\x1d\n" +
	"\n" +
	"value_json\x18\a \x01(\fR\tvalueJson\"\xcd\x01\n" +
	"\x1aRespondInteractionResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12-\n" +
	"\x12duplicate_response\x18\x03 \x01(\bR\x11duplicateResponse\x12-\n" +
	"\x12committed_sequence\x18\x04 \x01(\x04R\x11committedSequence\"\xe0\x01\n" +
	"\x10SnapshotEnvelope\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rlast_sequence\x18\x03 \x01(\x04R\flastSequence\x12F\n" +
	"\tlifecycle\x18\x04 \x01(\x0e2(.spice.agent.engine.v1.SnapshotLifecycleR\tlifecycle\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\fR\x06sha256\"t\n" +
	"\x15ExportSnapshotRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\x94\x01\n" +
	"\x16ExportSnapshotResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12C\n" +
	"\bsnapshot\x18\x02 \x01(\v2'.spice.agent.engine.v1.SnapshotEnvelopeR\bsnapshot\"\xe3\x02\n" +
	"\x15ImportSnapshotRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0fownership_epoch\x18\x02 \x01(\x04R\x0eownershipEpoch\x12.\n" +
	"\x13client_operation_id\x18\x03 \x01(\tR\x11clientOperationId\x12\x1c\n" +
	"\n" +
	"new_run_id\x18\x04 \x01(\tR\bnewRunId\x12G\n" +
	" expected_static_plan_fingerprint\x18\x05 \x01(\tR\x1dexpectedStaticPlanFingerprint\x12(\n" +
	"\x10expected_plan_id\x18\x06 \x01(\tR\x0eexpectedPlanId\x12C\n" +
	"\bsnapshot\x18\a \x01(\v2'.spice.agent.engine.v1.SnapshotEnvelopeR\bsnapshot\"\xbc\x01\n" +
	"\x16ImportSnapshotResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.spice.agent.common.v1.StatusR\x06status\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rnext_sequence\x18\x03 \x01(\x04R\fnextSequence\x12/\n" +
	"\x13duplicate_operation\x18\x04 \x01(\bR\x12duplicateOperation*\x8e\x01\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_ROLE_SYSTEM\x10\x01\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x03\x12\x15\n" +
	"\x11MESSAGE_ROLE_TOOL\x10\x04*\xf2\x04\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVENT_KIND_RUN_STARTED\x10\x01\x12\x1c\n" +
	"\x18EVENT_KIND_RUN_COMPLETED\x10\x02\x12\x19\n" +
	"\x15EVENT_KIND_RUN_FAILED\x10\x03\x12\x1c\n" +
	"\x18EVENT_KIND_RUN_CANCELLED\x10\x04\x12\x1b\n" +
	"\x17EVENT_KIND_TURN_STARTED\x10\x05\x12\x1d\n" +
	"\x19EVENT_KIND_TURN_COMPLETED\x10\x06\x12\x1a\n" +
	"\x16EVENT_KIND_TURN_FAILED\x10\a\x12\x1c\n" +
	"\x18EVENT_KIND_MODEL_STARTED\x10\b\x12\x1a\n" +
	"\x16EVENT_KIND_MODEL_DELTA\x10\t\x12\x1e\n" +
	"\x1aEVENT_KIND_MODEL_COMPLETED\x10\n" +
	"\x12\x1b\n" +
	"\x17EVENT_KIND_MODEL_FAILED\x10\v\x12\x1b\n" +
	"\x17EVENT_KIND_TOOL_STARTED\x10\f\x12\x1c\n" +
	"\x18EVENT_KIND_TOOL_PROGRESS\x10\r\x12\x1d\n" +
	"\x19EVENT_KIND_TOOL_COMPLETED\x10\x0e\x12\x1a\n" +
	"\x16EVENT_KIND_TOOL_FAILED\x10\x0f\x12\"\n" +
	"\x1eEVENT_KIND_INTERACTION_STARTED\x10\x10\x12$\n" +
	" EVENT_KIND_INTERACTION_COMPLETED\x10\x11\x12!\n" +
	"\x1dEVENT_KIND_INTERACTION_FAILED\x10\x12\x12$\n" +
	" EVENT_KIND_INTERACTION_CANCELLED\x10\x13*\xbc\x01\n" +
	"\x11SnapshotLifecycle\x12\"\n" +
	"\x1eSNAPSHOT_LIFECYCLE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSNAPSHOT_LIFECYCLE_SUSPENDED\x10\x01\x12 \n" +
	"\x1cSNAPSHOT_LIFECYCLE_COMPLETED\x10\x02\x12\x1d\n" +
	"\x19SNAPSHOT_LIFECYCLE_FAILED\x10\x03\x12 \n" +
	"\x1cSNAPSHOT_LIFECYCLE_CANCELLED\x10\x042\xca\x06\n" +
	"\rEngineService\x12a\n" +
	"\n" +
	"Initialize\x12(.spice.agent.engine.v1.InitializeRequest\x1a).spice.agent.engine.v1.InitializeResponse\x12U\n" +
	"\x06Health\x12$.spice.agent.engine.v1.HealthRequest\x1a%.spice.agent.engine.v1.HealthResponse\x12[\n" +
	"\bStartRun\x12&.spice.agent.engine.v1.StartRunRequest\x1a'.spice.agent.engine.v1.StartRunResponse\x12i\n" +
	"\fStreamEvents\x12*.spice.agent.engine.v1.StreamEventsRequest\x1a+.spice.agent.engine.v1.StreamEventsResponse0\x01\x12^\n" +
	"\tCancelRun\x12'.spice.agent.engine.v1.CancelRunRequest\x1a(.spice.agent.engine.v1.CancelRunResponse\x12y\n" +
	"\x12RespondInteraction\x120.spice.agent.engine.v1.RespondInteractionRequest\x1a1.spice.agent.engine.v1.RespondInteractionResponse\x12m\n" +
	"\x0eExportSnapshot\x12,.spice.agent.engine.v1.ExportSnapshotRequest\x1a-.spice.agent.engine.v1.ExportSnapshotResponse\x12m\n" +
	"\x0eImportSnapshot\x12,.spice.agent.engine.v1.ImportSnapshotRequest\x1a-.spice.agent.engine.v1.ImportSnapshotResponseB;Z9github.com/spice-framework/spice-agent/engine/v1;enginev1b\x06proto3"

var (
	file_spice_agent_engine_v1_engine_proto_rawDescOnce sync.Once
	file_spice_agent_engine_v1_engine_proto_rawDescData []byte
)

func file_spice_agent_engine_v1_engine_proto_rawDescGZIP() []byte {
	file_spice_agent_engine_v1_engine_proto_rawDescOnce.Do(func() {
		file_spice_agent_engine_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spice_agent_engine_v1_engine_proto_rawDesc), len(file_spice_agent_engine_v1_engine_proto_rawDesc)))
	})
	return file_spice_agent_engine_v1_engine_proto_rawDescData
}

var file_spice_agent_engine_v1_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_spice_agent_engine_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_spice_agent_engine_v1_engine_proto_goTypes = []any{
	(MessageRole)(0),                   // 0: spice.agent.engine.v1.MessageRole
	(EventKind)(0),                     // 1: spice.agent.engine.v1.EventKind
	(SnapshotLifecycle)(0),             // 2: spice.agent.engine.v1.SnapshotLifecycle
	(*ToolCallPart)(nil),               // 3: spice.agent.engine.v1.ToolCallPart
	(*ToolResultPart)(nil),             // 4: spice.agent.engine.v1.ToolResultPart
	(*ExtensionPart)(nil),              // 5: spice.agent.engine.v1.ExtensionPart
	(*ContentPart)(nil),                // 6: spice.agent.engine.v1.ContentPart
	(*Message)(nil),                    // 7: spice.agent.engine.v1.Message
	(*AgentDefinitionRef)(nil),         // 8: spice.agent.engine.v1.AgentDefinitionRef
	(*InitializeRequest)(nil),          // 9: spice.agent.engine.v1.InitializeRequest
	(*InitializeResponse)(nil),         // 10: spice.agent.engine.v1.InitializeResponse
	(*HealthRequest)(nil),              // 11: spice.agent.engine.v1.HealthRequest
	(*HealthResponse)(nil),             // 12: spice.agent.engine.v1.HealthResponse
	(*StartRunRequest)(nil),            // 13: spice.agent.engine.v1.StartRunRequest
	(*StartRunResponse)(nil),           // 14: spice.agent.engine.v1.StartRunResponse
	(*StreamEventsRequest)(nil),        // 15: spice.agent.engine.v1.StreamEventsRequest
	(*RunEvent)(nil),                   // 16: spice.agent.engine.v1.RunEvent
	(*StreamControl)(nil),              // 17: spice.agent.engine.v1.StreamControl
	(*StreamEventsResponse)(nil),       // 18: spice.agent.engine.v1.StreamEventsResponse
	(*CancelRunRequest)(nil),           // 19: spice.agent.engine.v1.CancelRunRequest
	(*CancelRunResponse)(nil),          // 20: spice.agent.engine.v1.CancelRunResponse
	(*RespondInteractionRequest)(nil),  // 21: spice.agent.engine.v1.RespondInteractionRequest
	(*RespondInteractionResponse)(nil), // 22: spice.agent.engine.v1.RespondInteractionResponse
	(*SnapshotEnvelope)(nil),           // 23: spice.agent.engine.v1.SnapshotEnvelope
	(*ExportSnapshotRequest)(nil),      // 24: spice.agent.engine.v1.ExportSnapshotRequest
	(*ExportSnapshotResponse)(nil),     // 25: spice.agent.engine.v1.ExportSnapshotResponse
	(*ImportSnapshotRequest)(nil),      // 26: spice.agent.engine.v1.ImportSnapshotRequest
	(*ImportSnapshotResponse)(nil),     // 27: spice.agent.engine.v1.ImportSnapshotResponse
	(*v1.ProtocolRange)(nil),           // 28: spice.agent.common.v1.ProtocolRange
	(*v1.BuildIdentity)(nil),           // 29: spice.agent.common.v1.BuildIdentity
	(*v1.CapabilitySet)(nil),           // 30: spice.agent.common.v1.CapabilitySet
	(*v1.Limits)(nil),                  // 31: spice.agent.common.v1.Limits
	(*v1.Status)(nil),                  // 32: spice.agent.common.v1.Status
	(*v1.ProtocolVersion)(nil),         // 33: spice.agent.common.v1.ProtocolVersion
	(*v1.Health)(nil),                  // 34: spice.agent.common.v1.Health
}
var file_spice_agent_engine_v1_engine_proto_depIdxs = []int32{
	3,  // 0: spice.agent.engine.v1.ContentPart.tool_call:type_name -> spice.agent.engine.v1.ToolCallPart
	4,  // 1: spice.agent.engine.v1.ContentPart.tool_result:type_name -> spice.agent.engine.v1.ToolResultPart
	5,  // 2: spice.agent.engine.v1.ContentPart.extension:type_name -> spice.agent.engine.v1.ExtensionPart
	0,  // 3: spice.agent.engine.v1.Message.role:type_name -> spice.agent.engine.v1.MessageRole
	6,  // 4: spice.agent.engine.v1.Message.parts:type_name -> spice.agent.engine.v1.ContentPart
	28, // 5: spice.agent.engine.v1.InitializeRequest.protocol:type_name -> spice.agent.common.v1.ProtocolRange
	29, // 6: spice.agent.engine.v1.InitializeRequest.client:type_name -> spice.agent.common.v1.BuildIdentity
	30, // 7: spice.agent.engine.v1.InitializeRequest.supported_capabilities:type_name -> spice.agent.common.v1.CapabilitySet
	30, // 8: spice.agent.engine.v1.InitializeRequest.required_capabilities:type_name -> spice.agent.common.v1.CapabilitySet
	31, // 9: spice.agent.engine.v1.InitializeRequest.requested_limits:type_name -> spice.agent.common.v1.Limits
	32, // 10: spice.agent.engine.v1.InitializeResponse.status:type_name -> spice.agent.common.v1.Status
	33, // 11: spice.agent.engine.v1.InitializeResponse.protocol:type_name -> spice.agent.common.v1.ProtocolVersion
	29, // 12: spice.agent.engine.v1.InitializeResponse.server:type_name -> spice.agent.common.v1.BuildIdentity
	30, // 13: spice.agent.engine.v1.InitializeResponse.capabilities:type_name -> spice.agent.common.v1.CapabilitySet
	31, // 14: spice.agent.engine.v1.InitializeResponse.limits:type_name -> spice.agent.common.v1.Limits
	34, // 15: spice.agent.engine.v1.InitializeResponse.health:type_name -> spice.agent.common.v1.Health
	32, // 16: spice.agent.engine.v1.HealthResponse.status:type_name -> spice.agent.common.v1.Status
	29, // 17: spice.agent.engine.v1.HealthResponse.server:type_name -> spice.agent.common.v1.BuildIdentity
	33, // 18: spice.agent.engine.v1.HealthResponse.protocol:type_name -> spice.agent.common.v1.ProtocolVersion
	34, // 19: spice.agent.engine.v1.HealthResponse.health:type_name -> spice.agent.common.v1.Health
	8,  // 20: spice.agent.engine.v1.StartRunRequest.definition:type_name -> spice.agent.engine.v1.AgentDefinitionRef
	7,  // 21: spice.agent.engine.v1.StartRunRequest.input:type_name -> spice.agent.engine.v1.Message
	32, // 22: spice.agent.engine.v1.StartRunResponse.status:type_name -> spice.agent.common.v1.Status
	1,  // 23: spice.agent.engine.v1.RunEvent.kind:type_name -> spice.agent.engine.v1.EventKind
	32, // 24: spice.agent.engine.v1.StreamControl.status:type_name -> spice.agent.common.v1.Status
	16, // 25: spice.agent.engine.v1.StreamEventsResponse.event:type_name -> spice.agent.engine.v1.RunEvent
	17, // 26: spice.agent.engine.v1.StreamEventsResponse.control:type_name -> spice.agent.engine.v1.StreamControl
	32, // 27: spice.agent.engine.v1.CancelRunResponse.status:type_name -> spice.agent.common.v1.Status
	32, // 28: spice.agent.engine.v1.RespondInteractionResponse.status:type_name -> spice.agent.common.v1.Status
	2,  // 29: spice.agent.engine.v1.SnapshotEnvelope.lifecycle:type_name -> spice.agent.engine.v1.SnapshotLifecycle
	32, // 30: spice.agent.engine.v1.ExportSnapshotResponse.status:type_name -> spice.agent.common.v1.Status
	23, // 31: spice.agent.engine.v1.ExportSnapshotResponse.snapshot:type_name -> spice.agent.engine.v1.SnapshotEnvelope
	23, // 32: spice.agent.engine.v1.ImportSnapshotRequest.snapshot:type_name -> spice.agent.engine.v1.SnapshotEnvelope
	32, // 33: spice.agent.engine.v1.ImportSnapshotResponse.status:type_name -> spice.agent.common.v1.Status
	9,  // 34: spice.agent.engine.v1.EngineService.Initialize:input_type -> spice.agent.engine.v1.InitializeRequest
	11, // 35: spice.agent.engine.v1.EngineService.Health:input_type -> spice.agent.engine.v1.HealthRequest
	13, // 36: spice.agent.engine.v1.EngineService.StartRun:input_type -> spice.agent.engine.v1.StartRunRequest
	15, // 37: spice.agent.engine.v1.EngineService.StreamEvents:input_type -> spice.agent.engine.v1.StreamEventsRequest
	19, // 38: spice.agent.engine.v1.EngineService.CancelRun:input_type -> spice.agent.engine.v1.CancelRunRequest
	21, // 39: spice.agent.engine.v1.EngineService.RespondInteraction:input_type -> spice.agent.engine.v1.RespondInteractionRequest
	24, // 40: spice.agent.engine.v1.EngineService.ExportSnapshot:input_type -> spice.agent.engine.v1.ExportSnapshotRequest
	26, // 41: spice.agent.engine.v1.EngineService.ImportSnapshot:input_type -> spice.agent.engine.v1.ImportSnapshotRequest
	10, // 42: spice.agent.engine.v1.EngineService.Initialize:output_type -> spice.agent.engine.v1.InitializeResponse
	12, // 43: spice.agent.engine.v1.EngineService.Health:output_type -> spice.agent.engine.v1.HealthResponse
	14, // 44: spice.agent.engine.v1.EngineService.StartRun:output_type -> spice.agent.engine.v1.StartRunResponse
	18, // 45: spice.agent.engine.v1.EngineService.StreamEvents:output_type -> spice.agent.engine.v1.StreamEventsResponse
	20, // 46: spice.agent.engine.v1.EngineService.CancelRun:output_type -> spice.agent.engine.v1.CancelRunResponse
	22, // 47: spice.agent.engine.v1.EngineService.RespondInteraction:output_type -> spice.agent.engine.v1.RespondInteractionResponse
	25, // 48: spice.agent.engine.v1.EngineService.ExportSnapshot:output_type -> spice.agent.engine.v1.ExportSnapshotResponse
	27, // 49: spice.agent.engine.v1.EngineService.ImportSnapshot:output_type -> spice.agent.engine.v1.ImportSnapshotResponse
	42, // [42:50] is the sub-list for method output_type
	34, // [34:42] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_spice_agent_engine_v1_engine_proto_init() }
func file_spice_agent_engine_v1_engine_proto_init() {
	if File_spice_agent_engine_v1_engine_proto != nil {
		return
	}
	file_spice_agent_engine_v1_engine_proto_msgTypes[3].OneofWrappers = []any{
		(*ContentPart_Text)(nil),
		(*ContentPart_ToolCall)(nil),
		(*ContentPart_ToolResult)(nil),
		(*ContentPart_Extension)(nil),
	}
	file_spice_agent_engine_v1_engine_proto_msgTypes[15].OneofWrappers = []any{
		(*StreamEventsResponse_Event)(nil),
		(*StreamEventsResponse_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spice_agent_engine_v1_engine_proto_rawDesc), len(file_spice_agent_engine_v1_engine_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spice_agent_engine_v1_engine_proto_goTypes,
		DependencyIndexes: file_spice_agent_engine_v1_engine_proto_depIdxs,
		EnumInfos:         file_spice_agent_engine_v1_engine_proto_enumTypes,
		MessageInfos:      file_spice_agent_engine_v1_engine_proto_msgTypes,
	}.Build()
	File_spice_agent_engine_v1_engine_proto = out.File
	file_spice_agent_engine_v1_engine_proto_goTypes = nil
	file_spice_agent_engine_v1_engine_proto_depIdxs = nil
}
