name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-module-release.yml@f29b7ce16f8d220e87bfae54469057d001944b7b
    with:
      module: github.com/spice-framework/spice-agent
      workflow_commit: f29b7ce16f8d220e87bfae54469057d001944b7b
