name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions: {}

jobs:
  release:
    name: Keylessly attest and publish
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: spice-framework/.github/.github/workflows/go-module-release.yml@9b35ae8173d76f3baf9c63d74189863bc6f59e86
    with:
      module: github.com/spice-framework/spice-agent
      workflow_commit: 9b35ae8173d76f3baf9c63d74189863bc6f59e86
